# Janela de Parzen

In [20]:
%matplotlib inline
#bibliotecas

from sklearn.datasets import make_blobs, make_moons, make_regression, load_iris
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from scipy.stats import gaussian_kde


from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

# Carregando Bancos de dados


In [21]:
dados = pd.read_csv("banco.csv")
dados = np.asarray(dados)
print(dados)

#pd.DataFrame(dados)


[[0 110.0 189.0 ... 18.666667999999998 0.50813884 '1.9108642']
 [0 86.0 187.0 ... 19.222220999999998 0.46332908 '1.9414649']
 [0 225.0 244.0 ... 17.11111 0.48014903 '1.9879022']
 ...
 [3 128.0 161.0 ... 10.888889 0.5409177 '+AC0-1.9963073']
 [3 150.0 158.0 ... 12.222222 0.50308645 '+AC0-1.9434487']
 [3 124.0 162.0 ... 14.555554999999998 0.4799313 '+AC0-2.0293121']]


In [22]:
#A dimensão dos dados
dados.shape

(2100, 20)

In [23]:
X = dados[0:2100, 1:20]
print(X)
print(X.shape)


[[110.0 189.0 9 ... 18.666667999999998 0.50813884 '1.9108642']
 [86.0 187.0 9 ... 19.222220999999998 0.46332908 '1.9414649']
 [225.0 244.0 9 ... 17.11111 0.48014903 '1.9879022']
 ...
 [128.0 161.0 9 ... 10.888889 0.5409177 '+AC0-1.9963073']
 [150.0 158.0 9 ... 12.222222 0.50308645 '+AC0-1.9434487']
 [124.0 162.0 9 ... 14.555554999999998 0.4799313 '+AC0-2.0293121']]
(2100, 19)


In [24]:
Y = dados[0:2100, 0]
print(Y)
print(Y.shape)

[0 0 0 ... 3 3 3]
(2100,)


In [29]:
gaussian_kde(X.transpose(), bw_method=0.2)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [27]:
kde = gaussian_kde(X.transpose(), bw_method=0.2)
kde.evaluate(dados[1000:2000].tranpose())


TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [7]:

from sklearn.neighbors.kde import KernelDensity
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print(X)
kde = KernelDensity(kernel='gaussian', bandwidth=0.2).fit(X)
kde.score_samples(X)

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


array([-0.41075698, -0.41075698, -0.41076071, -0.41075698, -0.41075698,
       -0.41076071])