# Crossvalidação

In [15]:
%matplotlib inline

from sklearn.datasets import make_blobs, make_moons, make_regression, load_iris
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 


from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

# Carregando Bancos de dados


In [16]:
dados = pd.read_csv("banco.csv")
dados = np.asarray(dados)
dados

#pd.DataFrame(dados)


array([[0, 110.0, 189.0, ..., 18.666667999999998, 0.50813884,
        '1.9108642'],
       [0, 86.0, 187.0, ..., 19.222220999999998, 0.46332908, '1.9414649'],
       [0, 225.0, 244.0, ..., 17.11111, 0.48014903, '1.9879022'],
       ...,
       [3, 128.0, 161.0, ..., 10.888889, 0.5409177, '+AC0-1.9963073'],
       [3, 150.0, 158.0, ..., 12.222222, 0.50308645, '+AC0-1.9434487'],
       [3, 124.0, 162.0, ..., 14.555554999999998, 0.4799313,
        '+AC0-2.0293121']], dtype=object)

In [17]:
#A dimensão dos dados
dados.shape

(2100, 20)

In [23]:
#Carregando o Banco de dados 2
view1 = dados[:, 0:10]                          ####  Tem q dividi o banco incluindo as classes

#esse comando so para vizualização. Usar sempre view.
dados2 = np.asarray(view1)
#pd.DataFrame(view1)
print(view1)
print(view1.shape)


[[0 110.0 189.0 ... 0.66666675 1.2222223 '1.1863422']
 [0 86.0 187.0 ... 0.7200825 1.4444445 '0.750309']
 [0 225.0 244.0 ... 2.1951127 2.9999998 '1.5202343']
 ...
 [3 128.0 161.0 ... 0.25185192 0.77777785 '0.16296278']
 [3 150.0 158.0 ... 1.6333338 1.388889 '0.41851807']
 [3 124.0 162.0 ... 1.1296295 2.0 '0.8888891']]
(2100, 10)


In [25]:
#Carregando o Banco de dados3

c_view2= dados[:,0]
V_view2 = dados[:,10:20]
print (V_view2)
print(V_view2.shape)


[[12.925925999999999 10.888889 9.222222 ... 18.666667999999998 0.50813884
  '1.9108642']
 [13.740741 11.666667 10.333333999999999 ... 19.222220999999998
  0.46332908 '1.9414649']
 [12.259259 10.333333999999999 9.333333999999999 ... 17.11111 0.48014903
  '1.9879022']
 ...
 [7.148148 5.5555553 10.888889 ... 10.888889 0.5409177 '+AC0-1.9963073']
 [8.444445 7.0 12.222222 ... 12.222222 0.50308645 '+AC0-1.9434487']
 [10.037037 8.0 14.555554999999998 ... 14.555554999999998 0.4799313
  '+AC0-2.0293121']]
(2100, 10)


In [26]:
#esse comando so para vizualização. 
dados33 = np.asarray(c_view2)
clas=pd.DataFrame(c_view2)
#print(clas)

#esse comando so para vizualização. Usar sempre view.
dados3 = np.asarray(V_view2)
R_Banco=pd.DataFrame(V_view2)
#print(R_Banco)

#concatenando as classes com o resto do banco
view2=pd.concat([clas, R_Banco], axis=1)
#print(view2)

#esse comando so para vizualização. Usar sempre view.
dados3 = np.asarray(view2)
#pd.DataFrame(view2)

print(dados3)
print(dados3.shape)

[[0 12.925925999999999 10.888889 ... 18.666667999999998 0.50813884
  '1.9108642']
 [0 13.740741 11.666667 ... 19.222220999999998 0.46332908 '1.9414649']
 [0 12.259259 10.333333999999999 ... 17.11111 0.48014903 '1.9879022']
 ...
 [3 7.148148 5.5555553 ... 10.888889 0.5409177 '+AC0-1.9963073']
 [3 8.444445 7.0 ... 12.222222 0.50308645 '+AC0-1.9434487']
 [3 10.037037 8.0 ... 14.555554999999998 0.4799313 '+AC0-2.0293121']]
(2100, 11)


# Estatísticas descritivas dos dados


In [38]:
dados = pd.read_csv("banco.csv")
dados.describe()

REGION-CENTROID-COL  REGION-CENTROID-ROW  REGION-PIXEL-COUNT  \
count          2100.000000          2100.000000              2100.0   
mean            124.940476           123.483333                 9.0   
std              72.858637            57.431428                 0.0   
min               1.000000            11.000000                 9.0   
25%              62.000000            81.000000                 9.0   
50%             121.000000           122.000000                 9.0   
75%             188.250000           171.250000                 9.0   
max             254.000000           251.000000                 9.0   

       SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2   VEDGE-MEAN     VEDGE-SD  \
count           2100.000000           2100.000000  2100.000000  2100.000000   
mean               0.014921              0.004550     1.890820     5.708299   
std                0.041024              0.023573     2.649453    44.989359   
min                0.000000              0.000000     0.000000     0.000000   
25%                0.000000              0.000000     0.722222     0.349603   
50%                0.000000              0.000000     1.277776     0.833333   
75%                0.000000              0.000000     2.222221     1.807406   
max                0.333333              0.222222    29.222221   991.718400   

        HEDGE-MEAN      HEDGE-SD  INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  \
count  2100.000000  2.100000e+03     2100.000000  2100.000000   2100.000000   
mean      2.406772  7.904224e+00       37.047654    32.806667     44.205556   
std       3.469954  5.347107e+01       38.135291    34.994538     43.510119   
min       0.000000 -1.589457e-08        0.000000     0.000000      0.000000   
25%       0.833332  4.216377e-01        7.472222     7.000000      9.666667   
50%       1.444444  9.897442e-01       21.666666    19.666668     27.777779   
75%       2.555556  2.251852e+00       53.277778    47.333332     65.000000   
max      44.722225  1.386329e+03      143.444440   137.111110    150.888890   

       RAWGREEN-MEAN   EXRED-MEAN  EXBLUE-MEAN  EXGREEN-MEAN   VALUE-MEAN  \
count    2100.000000  2100.000000  2100.000000   2100.000000  2100.000000   
mean       34.130741   -12.722963    21.473704     -8.750741    45.162381   
std        36.303768    11.588214    19.654107     11.606996    42.900582   
min         0.000000   -49.666668   -12.444445    -33.888890     0.000000   
25%         6.222222   -18.583333     4.305556    -17.000000    11.777778   
50%        20.444445   -10.888889    19.666666    -11.000000    28.666666   
75%        46.388888    -4.222222    36.111110     -3.222222    65.000000   
max       142.555560     9.888889    82.000000     24.666666   150.888890   

       SATURATION-MEAN     HUE-MEAN  
count      2100.000000  2100.000000  
mean          0.879188    -1.365147  
std          14.643927     1.544278  
min           0.000000    -3.044175  
25%           0.284934    -2.188539  
50%           0.375064    -2.052625  
75%           0.541005    -1.565745  
max         475.000000     2.912480

# Validação cruzada

In [39]:
#Validação Cruzada para o Banco 1

X = dados[:, 1:20]
y = dados[:, 0]
skf = StratifiedKFold(n_splits=10)

for train_index, test_index in skf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

###Como especificar quem é treino e teste

TypeError: unhashable type: 'slice'

In [40]:
#Validação Cruzada para o Banco 2

X = dados2[:, 1:10]
y = dados[:, 0]
skf = StratifiedKFold(n_splits=10)

for train_index, test_index in skf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

TypeError: unhashable type: 'slice'

In [41]:
#Validação Cruzada para o Banco 3

X = dados[:, 10:20]
y = dados[:, 0]
skf = StratifiedKFold(n_splits=10)

for train_index, test_index in skf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

TypeError: unhashable type: 'slice'

# Janela de parzen

In [42]:
#from scipy.stats import gaussian_kde

#kde = gaussian_kde(dados[1:1000,1:20].transpose(), bw_method=0.2)
#kde.evaluate(dados[1000:2000].tranpose())

# Classificador Bayesiano Gaussian

In [43]:

class BayesClassifier:
    
    mu = None
    cov = None
    n_classes = None
    
    def __init__(self):
        a = None
    
    def pred(self,x):
        prob_vect = np.zeros(self.n_classes)
        
        for i in range(self.n_classes):
            
            
            mnormal = multivariate_normal(mean=bc.mu[i], cov=bc.cov[i])
            
            # We use uniform priors
            prior = 1./self.n_classes
            
            prob_vect[i] = prior*mnormal.pdf(x)
            sumatory = 0.
            for j in range(self.n_classes):
                mnormal = multivariate_normal(mean=bc.mu[j], cov=bc.cov[j])
                sumatory += prior*mnormal.pdf(x)
            prob_vect[i] = prob_vect[i]/sumatory
        return prob_vect
        
    def fit(self, X,y):
        self.mu = []
        self.cov = []
        
        self.n_classes = np.max(y)+1
        
        for i in range(self.n_classes):
            Xc = X[y==i]
            
            mu_c = np.mean(Xc, axis=0)
            self.mu.append(mu_c)
            
            cov_c = np.zeros((X.shape[1], X.shape[1]))
            for j in range( Xc.shape[0]):
                a = Xc[j].reshape((X.shape[1],1))
                b = Xc[j].reshape((1,X.shape[1]))
                cov_ci = np.multiply(a, b)
                cov_c = cov_c+cov_ci
            cov_c = cov_c/float(X.shape[0])
            self.cov.append(cov_c)
        self.mu = np.asarray(self.mu)
        self.cov = np.asarray(self.cov)

In [53]:
#Carregando o Banco de dados 2
view1 = dados[:, 0:10]
print(view1)

[['GRASS' 110.0 189.0 ... 0.66666675 1.2222223 1.1863422]
 ['GRASS' 86.0 187.0 ... 0.7200825 1.4444445 0.750309]
 ['GRASS' 225.0 244.0 ... 2.1951127 2.9999998 1.5202343]
 ...
 ['CEMENT' 128.0 161.0 ... 0.25185192 0.77777785 0.16296278]
 ['CEMENT' 150.0 158.0 ... 1.6333338 1.388889 0.41851807]
 ['CEMENT' 124.0 162.0 ... 1.1296295 2.0 0.8888891]]


In [28]:
bc = BayesClassifier()

print (bc)

view1 = dados[:, 1:2]

bc.fit(X,Y)

In [ ]:
hit = 0.

for i in range(X_test.shape[0]):
    ypred = bc.pred(X_test[i])
    if np.argmax(ypred) == y_test[i]:
        hit += 1

print ("Not so naive Gaussian bayes score: "+str(hit/X_test.shape[0]))


# Classificador da soma





# TESTES UTILIZADOS




# Estimativa pontual e um intervalo de confiança para cada classificador

# Teste de Friedman

# Teste de Nemenyi 

In [ ]:
#intervalo de confiança para taxa de acerto?????


#salva as saidas dos dados

#np .  savetxt ( './training_set.csv' , training_data , delimiter = ',' )
#np .  savetxt ( './test_set.csv' , test_data , delimiter = ',' )

#janela de Parzen


In [37]:

from sklearn.neighbors.kde import KernelDensity
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print(X)
kde = KernelDensity(kernel='gaussian', bandwidth=0.2).fit(X)
kde.score_samples(X)

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


array([-0.41075698, -0.41075698, -0.41076071, -0.41075698, -0.41075698,
       -0.41076071])

In [49]:
from scipy import stats
import scipy as sp
import numpy as np
 
s = np.array([1,2,3,4,4,4,5,5,5,5,4,4,4,6,7,8])


In [60]:
from scipy import stats
import scipy as sp
import numpy as np
 
s = np.array([1,2,3,4,4,4,5,5,5,5,4,4,4,6,7,8])
s.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [56]:

s = np.array([1,2,3,4,4,4,5,5,5,5,4,4,4,6,7,8])
n, min_max, mean, var, skew, kurt = stats.describe(s)